# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/cyx/Desktop/EDA2/EDA2_TOP/EDA2_TOP.cache/wt [current_project]
set_property parent.project_path /home/cyx/Desktop/EDA2/EDA2_TOP/EDA2_TOP.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/cyx/Desktop/EDA2/CYX_IP_CATALOG [current_project]
update_ip_catalog
set_property ip_output_repo /home/cyx/Desktop/EDA2/EDA2_TOP/EDA2_TOP.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/cyx/Desktop/EDA2/EDA2_TOP/EDA2_TOP.srcs/sources_1/new/EDA2_fsm.v
  /home/cyx/Desktop/EDA2/EDA2_TOP/EDA2_TOP.srcs/sources_1/new/coins_input.v
  /home/cyx/Desktop/EDA2/EDA2_TOP/EDA2_TOP.srcs/sources_1/new/key_scan_hardware_test.v
  /home/cyx/Desktop/EDA2/EDA2_TOP/EDA2_TOP.srcs/sources_1/new/keys_scan.v
  /home/cyx/Desktop/EDA2/EDA2_TOP/EDA2_TOP.srcs/sources_1/new/timer.v
  /home/cyx/Desktop/EDA2/EDA2_TOP/EDA2_TOP.srcs/sources_1/new/EDA2_TOP.v
}
read_ip -quiet /home/cyx/Desktop/EDA2/EDA2_TOP/EDA2_TOP.srcs/sources_1/ip/Digits_dynamic_display_0/Digits_dynamic_display_0.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/cyx/Desktop/EDA2/EDA2_TOP/EDA2_TOP.srcs/constrs_1/new/con_1.xdc
set_property used_in_implementation false [get_files /home/cyx/Desktop/EDA2/EDA2_TOP/EDA2_TOP.srcs/constrs_1/new/con_1.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top EDA2_TOP -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef EDA2_TOP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file EDA2_TOP_utilization_synth.rpt -pb EDA2_TOP_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
