#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Dec 07 20:14:41 CST 2019
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim EDA2_TOP_tb_behav -key {Behavioral:sim_1:Functional:EDA2_TOP_tb} -tclbatch EDA2_TOP_tb.tcl -view /home/cyx/Desktop/EDA2/EDA2_TOP/EDA2_fsm_tb_behav.wcfg -log simulate.log"
xsim EDA2_TOP_tb_behav -key {Behavioral:sim_1:Functional:EDA2_TOP_tb} -tclbatch EDA2_TOP_tb.tcl -view /home/cyx/Desktop/EDA2/EDA2_TOP/EDA2_fsm_tb_behav.wcfg -log simulate.log

