#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Dec 03 14:06:18 CST 2019
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim EDA2_fsm_tb_func_impl -key {Post-Implementation:sim_1:Functional:EDA2_fsm_tb} -tclbatch EDA2_fsm_tb.tcl -log simulate.log"
xsim EDA2_fsm_tb_func_impl -key {Post-Implementation:sim_1:Functional:EDA2_fsm_tb} -tclbatch EDA2_fsm_tb.tcl -log simulate.log

